### ISSUE TITLE
Better encoding support

### ISSUE THREAD

**Issue by Martinligabue** [LuisMayo/ace-attorney-telegram-bot#6]
Some characters are not displayed correctly, is it possible to make it compatible with the same encoding that Telegram uses?
As example, my name should be ℳartin
but it appears as
![image](https://user-images.githubusercontent.com/22115672/111375819-fe0aaf80-869e-11eb-93bb-7f84b28c72e9.png)

**Comment by LuisMayo** [comment]
Thanks again for the issue!
I'm not sure to what extent this may possible. Since we're trying to use official fonts.
In any case this issue is being tracked here: https://github.com/LuisMayo/ace-attorney-bot/issues/11
Thanks!

**Comment by Martinligabue** [comment]
oh there's a main repo, thanks, and thanks for the explanation
