### ISSUE TITLE
Add support for Russian characters

### ISSUE THREAD

**Issue by cofob** [LuisMayo/ace-attorney-telegram-bot#8]
Instead of letters, various symbols are displayed, most likely the font without Cyrillic support is to blame.

**Comment by LuisMayo** [comment]
Hi and thanks for the issue

This issues is being tracked already in this issues

https://github.com/LuisMayo/ace-attorney-bot/issues/11

https://github.com/LuisMayo/ace-attorney-bot/issues/22

Thanks!
